#include "stm32f4xx.h"
#include "clock and perif.h"


void initSystem(void)
{
	initClock();
	initTimer();
	initI2c();
	initAdc();
	initButton();	
}

void initClock(void)
{
	//Frequency HSE - 25 MHz
	RCC->CR |= RCC_CR_HSEON    ;
	
	while (!(RCC->CR & RCC_CR_HSERDY))
	{
	}
		
	RCC->CFGR |=  RCC_CFGR_SW_HSE;
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN |
									RCC_AHB1ENR_GPIOBEN | 
									RCC_AHB1ENR_GPIOCEN ;
									
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN |
									RCC_APB1ENR_TIM5EN |
									RCC_APB1ENR_TIM4EN |
									RCC_APB1ENR_TIM3EN;
	
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN  |
									RCC_APB2ENR_TIM1EN	|
									RCC_APB2ENR_SYSCFGEN;
	
	GPIOC->MODER |= GPIO_MODER_MODER13_0;
}

void initI2c(void)
{
	//Don't forget to enable clock in GPIOB and I2C1
	
	GPIOB->MODER |= GPIO_MODER_MODER8_1;  //i2c scl
	GPIOB->MODER |= GPIO_MODER_MODER9_1;	//i2c sda
	
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR9_1;
	
	GPIOB->OTYPER |= GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9;
	
	GPIOB->AFR[1] |= GPIO_AFRH_AFRH0_2 | GPIO_AFRH_AFRH1_2;
	
	I2C1->CR2 &= ~I2C_CR2_FREQ;
	I2C1->CR2 |= 25;
	
	I2C1->CCR &= ~I2C_CCR_CCR;
	I2C1->CCR |= 250;
	
	I2C1->TRISE = 25;
	I2C1->CR1 |= I2C_CR1_ACK;
	
	I2C1->CR1 |= I2C_CR1_PE;
}	

void initAdc(void)
{
	//Don't forget to enable clock in GPIOA and ADC1
	GPIOA->MODER |= GPIO_MODER_MODER1;
	GPIOB->MODER |= GPIO_MODER_MODER0;
	GPIOA->MODER |= GPIO_MODER_MODER6;
	
	
	ADC1->CR2 |= ADC_CR2_ADON | ADC_CR2_EXTEN_0 | ADC_CR2_EXTSEL_3;
	ADC1->SMPR2 = ADC_SMPR2_SMP8_0; 
	NVIC_EnableIRQ(ADC_IRQn);
	ADC1->CR1 = ADC_CR1_EOCIE;
	
	ADC1->SQR1 = 0x00000000;
	ADC1->SQR2 = 0x00000000;
	ADC1->SQR3 = 0x00000008; 
	ADC1->CR2 |= ADC_CR2_SWSTART;
}

void initTimer(void)
{
	//Test Timer - Time 1s 
	TIM5->ARR = 25000;
	TIM5->PSC = 1000-1;
	TIM5->DIER |= TIM_DIER_UIE;
	TIM5->CR1 |= TIM_CR1_CEN;
	NVIC_EnableIRQ(TIM5_IRQn);
	
	//Timer 1 sec
	TIM4->ARR = 25000;
	TIM4->PSC = 1000-1;
	TIM4->DIER |= TIM_DIER_UIE;
	TIM4->CR1 |= TIM_CR1_CEN;
	NVIC_EnableIRQ(TIM4_IRQn);
	
	//ADC Timer - Time 10ms
	TIM3->DIER |= TIM_DIER_UIE;
	TIM3->ARR = 250;
	TIM3->PSC = 1000-1;
	TIM3->CR1 |= TIM_CR1_CEN;
	TIM3->CR2 |= TIM_CR2_MMS_1;
	
	//PWM Timer
	TIM1->PSC = 2500*2-1;
	TIM1->ARR = 1000;
	TIM1->DIER |= TIM_DIER_UIE;
	//TIM1->CR1 |= TIM_CR1_OPM;
	TIM1->CCER |= TIM_CCER_CC2E | TIM_CCER_CC3NE | TIM_CCER_CC3E;
	//Channel 2 in PWM mode PA9
	TIM1->CCMR1 = TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1;
	//Channel 3 in PWM mode PB15 invert
	TIM1->CCMR2 = TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 ;
	
	//TIM1->CR1 |= TIM_CR1_UDIS;	
	TIM1->CR1 &= ~TIM_CR1_DIR;
	//TIM1->CR1 |= TIM_CR1_CMS;
	TIM1->CR1 &= ~TIM_CR1_CMS;
	TIM1->BDTR |= TIM_BDTR_MOE;

	//TIM1->BDTR |= TIM_BDTR_LOCK_0;
	//TIM1->BDTR |= TIM_BDTR_DTG;
	//TIM1->CR1 |= TIM_CR1_CEN;
	//NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
	
	//Channel 2 TIM1 PA9
	GPIOA->MODER |= GPIO_MODER_MODER9_1; 
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH1_0;
	
	//Channel 3 TIM1 PB15 Invert
	GPIOB->MODER |= GPIO_MODER_MODER15_1; 
	GPIOB->AFR[1] |= GPIO_AFRH_AFRH7_0;
}

void initButton(void)
{
	//Button 4
	GPIOB->MODER &= ~GPIO_MODER_MODER3;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR3;
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR3;
	EXTI->IMR |= EXTI_IMR_MR3;
	EXTI->FTSR |= EXTI_FTSR_TR3;
  //EXTI->RTSR |= EXTI_RTSR_TR3;
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI3_PB;
	NVIC_EnableIRQ(EXTI3_IRQn);

	
	//Button 1
	GPIOB->MODER &= ~GPIO_MODER_MODER4;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR4;
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR4;
	EXTI->IMR |= EXTI_IMR_MR4;
	EXTI->FTSR |= EXTI_FTSR_TR4;
  //EXTI->RTSR |= EXTI_RTSR_TR4;
	SYSCFG->EXTICR[1] |= SYSCFG_EXTICR2_EXTI4_PB;
	NVIC_EnableIRQ(EXTI4_IRQn);
	
	
	//Button 3
	GPIOB->MODER &= ~GPIO_MODER_MODER5;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR5;
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR5;
	EXTI->IMR |= EXTI_IMR_MR5;
	EXTI->FTSR |= EXTI_FTSR_TR5;
  //EXTI->RTSR |= EXTI_RTSR_TR5;
	SYSCFG->EXTICR[1] |= SYSCFG_EXTICR2_EXTI5_PB;
	NVIC_EnableIRQ(EXTI9_5_IRQn);
	
	//Button 2
	GPIOB->MODER &= ~GPIO_MODER_MODER6;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR6;
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR6;
	EXTI->IMR |= EXTI_IMR_MR6;
	EXTI->FTSR |= EXTI_FTSR_TR6;
  //EXTI->RTSR |= EXTI_RTSR_TR6;
	SYSCFG->EXTICR[1] |= SYSCFG_EXTICR2_EXTI6_PB;
	NVIC_EnableIRQ(EXTI9_5_IRQn);	
}